import { Colaborador } from './types';
import { v4 as uuidv4 } from 'uuid';

export const initialData: Colaborador[] = [
  {
    id: uuidv4(),
    nome: 'João',
    apelido: 'Silva',
    sexo: 'Masculino',
    dataNascimento: '1985-04-12',
    empresa: 'NUKE',
    departamento: 'Operação',
    cargo: 'Operador de Máquinas',
    supervisor: 'Carlos Mendes',
    dataAdmissao: '2019-02-15',
    dataFimContrato: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    estado: 'Activo',
    contacto: '+258 84 123 4567',
    email: 'joao.silva@nuke.co.mz',
    salario: 45000,
    nuit: '123456789',
    observacoes: 'Excelente desempenho'
  },
  {
    id: uuidv4(),
    nome: 'Ana',
    apelido: 'Costa',
    sexo: 'Feminino',
    dataNascimento: '1990-08-22',
    empresa: 'PCS',
    departamento: 'Administração',
    cargo: 'Gestora de RH',
    supervisor: 'Marta Ribeiro',
    dataAdmissao: '2021-05-10',
    dataFimContrato: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    estado: 'Activo',
    contacto: '+258 82 987 6543',
    email: 'ana.costa@pcs.co.mz',
    salario: 65000,
    nuit: '987654321',
    observacoes: ''
  },
  {
    id: uuidv4(),
    nome: 'Pedro',
    apelido: 'Santos',
    sexo: 'Masculino',
    dataNascimento: '1982-11-05',
    empresa: 'ZMAX',
    departamento: 'Oficina',
    cargo: 'Mecânico Chefe',
    supervisor: 'Rui Manuel',
    dataAdmissao: '2015-10-01',
    estado: 'Activo',
    contacto: '+258 84 555 1234',
    email: 'pedro.santos@zmax.co.mz',
    salario: 75000,
    nuit: '456123789',
    observacoes: 'Precisa de formação de segurança este ano'
  },
  {
    id: uuidv4(),
    nome: 'Maria',
    apelido: 'João',
    sexo: 'Feminino',
    dataNascimento: '1995-02-14',
    empresa: 'MICC',
    departamento: 'Safety',
    cargo: 'Técnica de HST',
    supervisor: 'Luís Alberto',
    dataAdmissao: '2022-03-20',
    estado: 'Activo',
    contacto: '+258 84 777 8899',
    email: 'maria.joao@micc.co.mz',
    salario: 55000,
    nuit: '321654987',
    observacoes: ''
  },
  {
    id: uuidv4(),
    nome: 'Carlos',
    apelido: 'Mendes',
    sexo: 'Masculino',
    dataNascimento: '1978-06-30',
    empresa: 'NUKE',
    departamento: 'Operação',
    cargo: 'Supervisor de Turno',
    supervisor: 'Diretor de Operações',
    dataAdmissao: '2010-01-15',
    estado: 'Activo',
    contacto: '+258 82 111 2233',
    email: 'carlos.mendes@nuke.co.mz',
    salario: 95000,
    nuit: '159753456',
    observacoes: ''
  },
  {
    id: uuidv4(),
    nome: 'Sofia',
    apelido: 'Reis',
    sexo: 'Feminino',
    dataNascimento: '1988-09-10',
    empresa: 'PCS',
    departamento: 'Warehouse',
    cargo: 'Fiel de Armazém',
    supervisor: 'José Lima',
    dataAdmissao: '2018-07-01',
    estado: 'Despedido',
    contacto: '+258 84 444 5566',
    email: 'sofia.reis@pcs.co.mz',
    salario: 40000,
    nuit: '852963741',
    observacoes: 'Rescisão por justa causa'
  }
];
